<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="author" content="Zaid Daba\'een - Trialize"/>
        <meta property="og:type"   content="website" />
        <meta property="og:image"  content="<?php echo $this->basePath('images/shorten_logo.png') ?>" />
        <!-- <meta name="google-site-verification" content="" /> replace or remove & see what we can do -->

        <link rel="icon" type="image/vnd.microsoft.icon" href="<?php echo $this->basePath('images/shorten_logo.png') ?>" />
        <link rel="icon" type="image/png" href="<?php echo $this->basePath('images/shorten_logo.png') ?>" />
        <link rel="apple-touch-icon" href="<?php echo $this->basePath('images/shorten_logo.png') ?>" />
        <link rel="shortcut icon" href="<?php echo $this->basePath('images/shorten_logo.png') ?>" />

		<?php echo $this->headTitle($this->translate('Trialize'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php
		echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<script>
			var $basePath = "<?php echo $this->basePath() ?>";
		</script>
		
		<?php
		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/shorten_logo.png'))
			->prependStylesheet($this->basePath() . '/css/style.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
			->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
			->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css')
		?>
		<?php
		echo $this->headScript()
			->appendFile($this->basePath() . '/js/jquery.min.js')
			->appendFile($this->basePath() . '/js/bootstrap.min.js')
			->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->appendFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->appendFile($this->basePath() . '/js/doT.js')
		;
		
		$this->inlineScript()
			->appendFile($this->basePath() . '/js/hash.js');
		?>

	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>

					<a class="navbar-brand" href="<?php echo $this->url('home') ?>" style="padding: 15px 15px;">
						<span><img src="<?php echo $this->basePath('images/shorten_logo.png') ?>" alt="Shorten" style="width: 20px;"/></span>
						&nbsp;<?php echo $this->translate('Trialize') ?>
					</a>

				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<?php if ($this->action != 'login') { ?>
							<li>
								<a href="<?php echo $this->url('index', ['action' => 'create']) ?>"><?php echo $this->translate('New App Trial') ?></a>
							</li>
							<li>
								<a href="<?php echo $this->url('index', ['action' => 'logout']) ?>"><?php echo $this->translate('Logout') ?></a>
							</li>
						<?php } ?>
						<!--							
						<?php if (isset($_SESSION['staff_id'])) { ?>
															
						<?php } ?>
						-->
					</ul>
				</div> 
			</div>
		</nav>
		<div class="container">
			<br /><br />
			<?php echo $this->content; ?>
		</div>
		<hr>
		<footer align="center">
			<p>&copy; 2014 - <?php echo date('Y') ?> by Zaid Daba'een. <?php echo $this->translate('All rights reserved.') ?></p>
		</footer>

		<script type="text/plain" id="generateOptionTemplate">
			<option value="{{=it.id}}">{{=it.name}}</option>
		</script>


		
		<?php echo $this->inlineScript() ?>
	</body>
</html>
